spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: 'jdbc:mysql://localhost:3306/acropolisdev'
    username: root
    password: root
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: 'DEBUG'
        type:
          descriptor:
            sql:
              BasicBinder: 'TRACE'
