version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:10.0.2-jdk-sid
      - image: 'mysql:8'
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_PASSWORD=root
          - MYSQL_DATABASE=acropolisdev
    steps:
    - checkout
    - run:
        name: Take Ownership
        command: chmod +x ./gradlew
    - run:
        name: Build
        command: ./gradlew build -PrunIntegrationTests --debug
    - run:
        name: Test coverage
        command: ./gradlew jacocoTestReport
    - run:
        name: Create master coverage report
        command: ./gradlew codeCoverageReport
    - run:
        name: Upload coverage report
        command: >-
          apk update
          && apk add bash
          && apk add curl
          && bash -c "bash <(curl -s https://codecov.io/bash)"
