version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:10.0.2-jdk-sid
      - image: 'mysql:8'
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_PASSWORD=root
          - MYSQL_DATABASE=acropolisdev
    steps:
    - checkout
    - run:
        name: Take Ownership
        command: chmod +x ./gradlew
    - run:
        name: Build
        command: ./gradlew build -PrunIntegrationTests --debug > build.log
    - store_artifacts:
        path: build.log
        destination: build.log
    - run:
        name: Test coverage
        command: ./gradlew jacocoTestReport
    - run:
        name: Create master coverage report
        command: ./gradlew codeCoverageReport
    - run:
        name: Upload coverage report
        command: >-
          sudo apt-get update
          && sudo apt-get install bash
          && sudo apt-get install curl
          && bash -c "bash <(curl -s https://codecov.io/bash)"
