version: 2
jobs:
  build:
    docker:
    - image: openjdk:8-alpine
    steps:
    - checkout
    - run:
        name: Build
        command: gradle build
    - run:
        name: Test
        command: gradle test
