version: 2
jobs:
  build:
    docker:
    - image: openjdk:8-alpine
    steps:
    - checkout
    - run:
        name: Take Ownership
        command: chmod +x ./gradlew
    - run:
        name: Build
        command: ./gradlew build
    - run:
        name: Test coverage
        command: ./gradlew jacocoTestReport
    - run:
        name: Create master coverage report
        command: ./gradlew codeCoverageReport
    - run:
        name: Upload coverage report
        command: pip install codecov && codecov